version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27117:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - app-network

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "9000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_SERVER_AUTH_CREDENTIALS=admin:admin
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=basic
    networks:
      - app-network

volumes:
  mongodb_data:
  chromadb_data:

networks:
  app-network:
    driver: bridge