"use client"

import * as React from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Button } from "@/components/ui/button"

interface LegislationDocument {
  _id: string
  title: string
  year: string
  type: string
  no: string
}

export default function LegislationPage() {
  const router = useRouter()
  const [documents, setDocuments] = React.useState<LegislationDocument[]>([])

  // Fetch documents on mount
  React.useEffect(() => {
    fetch("/api/legislation")
      .then((res) => res.json())
      .then(setDocuments)
      .catch(console.error)
  }, [])

  return (
    <div className="container mx-auto py-8">
      <div className="mb-6">
        <h1 className="text-2xl font-bold mb-2">Explore the Legislative Data Model</h1>
        <p className="text-muted-foreground mb-2">
          This section lets you browse the internal data model used to power our retrieval tools and chatbot. You can:
        </p>
        <ul className="list-disc pl-6 text-muted-foreground mb-2">
          <li>View individual fragments of legislation (e.g., sections, subsections).</li>
          <li>See context summaries for each fragment, generated by an AI model to help provide broader context.</li>
        </ul>
        <p className="text-muted-foreground text-sm">
          <strong>Note:</strong> Only a subset of Acts is included for this prototype.
        </p>
      </div>

      <div className="flex justify-between items-center mb-8">
        <h1 className="text-2xl font-bold">Legislation Documents</h1>
      </div>

      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Title</TableHead>
              <TableHead>Year</TableHead>
              <TableHead>Number</TableHead>
              <TableHead className="w-[100px]">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {documents.map((doc) => (
              <TableRow key={doc._id}>
                <TableCell>
                  <Link
                    href={`/legislation/${doc._id}`}
                    className="text-foreground hover:underline"
                  >
                    {doc.title}
                  </Link>
                </TableCell>
                <TableCell>{doc.year}</TableCell>
                <TableCell>{doc.no}</TableCell>
                <TableCell>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => router.push(`/legislation/${doc._id}`)}
                  >
                    View
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}